services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketlens
    ports:
      - "5432:5432"
    volumes:
      - marketlens_pg:/var/lib/postgresql/data

volumes:
  marketlens_pg:
